version: "3"

services:
  rsshub:
    # image: ${GITEE_DOCKER_IMAGE}
    build: .
    restart: always
    ports:
      - "1200:1200"
    environment:
      NODE_ENV: production
      PORT: 1200
      TZ: "Asia/Shanghai"

